version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: devtree_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: linktree_node_typescript
    volumes:
      - mongodb_data:/data/db
    networks:
      - devtree_network

volumes:
  mongodb_data:
    driver: local

networks:
  devtree_network:
    driver: bridge
